/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Visao.Alterar.AlterarGarcom;
import Visao.Alterar.AlterarGerente;
import Visao.Alterar.AlterarProduto;
import Visao.Cadastrar.CadastraGarcom;
import Visao.Cadastrar.CadastrarGerente;
import Visao.Cadastrar.CadastrarMesas;
import Visao.Cadastrar.CadastrarProduto;
import Visao.Consultar.ConsultarGarcon;
import Visao.Consultar.ConsultarGerente;
import Visao.Consultar.ConsultarMesas;
import Visao.Consultar.ConsultarProduto;
import Visao.Excluir.ExcluirGarcom;
import Visao.Excluir.ExcluirGerente;
import Visao.Excluir.ExcluirMesa;
import Visao.Excluir.ExcluirProduto;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author cleil
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIcon();
       
    }
     public void MoverBtnCad(){
        BtnCad.setBackground(new Color(105,101,181) );
    }
    public void ExitBtnCad(){
         BtnCad.setBackground(new Color(119,240,75));
    }
     public void MoverBtnCon(){
        BtnCon.setBackground(new Color(105,101,181) );
    }
    public void ExitBtnCon(){
         BtnCon.setBackground(new Color(0,51,51));
    }
     public void MoverBtnAlt(){
        BtnAl.setBackground(new Color(105,101,181) );
    }
    public void ExitBtnAlt(){
         BtnAl.setBackground(new Color(255,255,51));
    }
      public void MoverBtnEx(){
        BtnEx.setBackground(new Color(105,101,181) );
    }
    public void ExitBtnEx(){
         BtnEx.setBackground(new Color(252,25,39));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BtnCad = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        BtnCon = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        BtnAl = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        BtnEx = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        BtnEx1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        BtnCad1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnCon1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(250, 35, 81));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 35, 81));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(254, 83, 98));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/manager.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 280, -1));

        jPanel8.setBackground(new java.awt.Color(0, 51, 51));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mesas");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 73, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 74, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 19, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 19, Short.MAX_VALUE)))
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        BtnCad.setBackground(new java.awt.Color(119, 240, 75));
        BtnCad.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnCadMouseMoved(evt);
            }
        });
        BtnCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCadMouseExited(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/plus.png"))); // NOI18N
        jLabel18.setText("Cadastrar");

        javax.swing.GroupLayout BtnCadLayout = new javax.swing.GroupLayout(BtnCad);
        BtnCad.setLayout(BtnCadLayout);
        BtnCadLayout.setHorizontalGroup(
            BtnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(BtnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnCadLayout.createSequentialGroup()
                    .addGap(0, 32, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(0, 33, Short.MAX_VALUE)))
        );
        BtnCadLayout.setVerticalGroup(
            BtnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(BtnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnCadLayout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        jPanel4.add(BtnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 180, 40));

        BtnCon.setBackground(new java.awt.Color(0, 51, 51));
        BtnCon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnConMouseMoved(evt);
            }
        });
        BtnCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnConMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder.png"))); // NOI18N
        jLabel19.setText("Consultar");

        javax.swing.GroupLayout BtnConLayout = new javax.swing.GroupLayout(BtnCon);
        BtnCon.setLayout(BtnConLayout);
        BtnConLayout.setHorizontalGroup(
            BtnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(BtnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnConLayout.createSequentialGroup()
                    .addGap(0, 33, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 34, Short.MAX_VALUE)))
        );
        BtnConLayout.setVerticalGroup(
            BtnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(BtnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnConLayout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        jPanel4.add(BtnCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        BtnAl.setBackground(new java.awt.Color(255, 255, 51));
        BtnAl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnAlMouseMoved(evt);
            }
        });
        BtnAl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAlMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAlMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pencil-edit-button.png"))); // NOI18N
        jLabel20.setText("Alterar");

        javax.swing.GroupLayout BtnAlLayout = new javax.swing.GroupLayout(BtnAl);
        BtnAl.setLayout(BtnAlLayout);
        BtnAlLayout.setHorizontalGroup(
            BtnAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(BtnAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnAlLayout.createSequentialGroup()
                    .addGap(0, 46, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 46, Short.MAX_VALUE)))
        );
        BtnAlLayout.setVerticalGroup(
            BtnAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(BtnAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnAlLayout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        jPanel4.add(BtnAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        BtnEx.setBackground(new java.awt.Color(252, 25, 39));
        BtnEx.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnExMouseMoved(evt);
            }
        });
        BtnEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnExMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnExMouseExited(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/rubbish-bin.png"))); // NOI18N
        jLabel21.setText("Exluir");

        javax.swing.GroupLayout BtnExLayout = new javax.swing.GroupLayout(BtnEx);
        BtnEx.setLayout(BtnExLayout);
        BtnExLayout.setHorizontalGroup(
            BtnExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(BtnExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnExLayout.createSequentialGroup()
                    .addGap(0, 50, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addGap(0, 50, Short.MAX_VALUE)))
        );
        BtnExLayout.setVerticalGroup(
            BtnExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(BtnExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnExLayout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        jPanel4.add(BtnEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gerente");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 67, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 68, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 19, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 19, Short.MAX_VALUE)))
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        BtnEx1.setBackground(new java.awt.Color(252, 25, 39));
        BtnEx1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnEx1MouseMoved(evt);
            }
        });
        BtnEx1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEx1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEx1MouseExited(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/rubbish-bin.png"))); // NOI18N
        jLabel25.setText("Exluir");

        javax.swing.GroupLayout BtnEx1Layout = new javax.swing.GroupLayout(BtnEx1);
        BtnEx1.setLayout(BtnEx1Layout);
        BtnEx1Layout.setHorizontalGroup(
            BtnEx1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(BtnEx1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnEx1Layout.createSequentialGroup()
                    .addGap(0, 50, Short.MAX_VALUE)
                    .addComponent(jLabel25)
                    .addGap(0, 50, Short.MAX_VALUE)))
        );
        BtnEx1Layout.setVerticalGroup(
            BtnEx1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(BtnEx1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnEx1Layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jLabel25)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        jPanel4.add(BtnEx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        BtnCad1.setBackground(new java.awt.Color(119, 240, 75));
        BtnCad1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnCad1MouseMoved(evt);
            }
        });
        BtnCad1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCad1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCad1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCad1MouseExited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/plus.png"))); // NOI18N
        jLabel22.setText("Cadastrar");

        javax.swing.GroupLayout BtnCad1Layout = new javax.swing.GroupLayout(BtnCad1);
        BtnCad1.setLayout(BtnCad1Layout);
        BtnCad1Layout.setHorizontalGroup(
            BtnCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(BtnCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnCad1Layout.createSequentialGroup()
                    .addGap(0, 32, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 33, Short.MAX_VALUE)))
        );
        BtnCad1Layout.setVerticalGroup(
            BtnCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(BtnCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnCad1Layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        jPanel4.add(BtnCad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dinning-table (1).png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 130, -1));

        BtnCon1.setBackground(new java.awt.Color(0, 51, 51));
        BtnCon1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnCon1MouseMoved(evt);
            }
        });
        BtnCon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCon1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCon1MouseExited(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder.png"))); // NOI18N
        jLabel23.setText("Consultar");

        javax.swing.GroupLayout BtnCon1Layout = new javax.swing.GroupLayout(BtnCon1);
        BtnCon1.setLayout(BtnCon1Layout);
        BtnCon1Layout.setHorizontalGroup(
            BtnCon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(BtnCon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnCon1Layout.createSequentialGroup()
                    .addGap(0, 33, Short.MAX_VALUE)
                    .addComponent(jLabel23)
                    .addGap(0, 34, Short.MAX_VALUE)))
        );
        BtnCon1Layout.setVerticalGroup(
            BtnCon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(BtnCon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnCon1Layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jLabel23)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        jPanel4.add(BtnCon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 730, 490));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 8, 22));
        jLabel2.setText("Proprietário");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sign-out.png"))); // NOI18N
        jLabel9.setText("Sair");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remove.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remove-button.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Baking Lion - Personal Use", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Restaurante 2019");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 70));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved

    }//GEN-LAST:event_jLabel3MouseMoved

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void BtnCadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCadMouseMoved
        MoverBtnCad();
    }//GEN-LAST:event_BtnCadMouseMoved

    private void BtnCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCadMouseClicked
       new CadastrarGerente().setVisible(true);
      
    }//GEN-LAST:event_BtnCadMouseClicked

    private void BtnCadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCadMouseExited
        ExitBtnCad();
    }//GEN-LAST:event_BtnCadMouseExited

    private void BtnConMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConMouseMoved
       MoverBtnCon();
    }//GEN-LAST:event_BtnConMouseMoved

    private void BtnConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConMouseClicked
        new ConsultarGerente().setVisible(true);
       
    }//GEN-LAST:event_BtnConMouseClicked

    private void BtnConMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConMouseExited
        ExitBtnCon();
    }//GEN-LAST:event_BtnConMouseExited

    private void BtnAlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAlMouseMoved
        MoverBtnAlt();
    }//GEN-LAST:event_BtnAlMouseMoved

    private void BtnAlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAlMouseClicked
        new AlterarGerente().setVisible(true);
       
    }//GEN-LAST:event_BtnAlMouseClicked

    private void BtnAlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAlMouseExited
        ExitBtnAlt();
    }//GEN-LAST:event_BtnAlMouseExited

    private void BtnExMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExMouseMoved
       MoverBtnEx();
    }//GEN-LAST:event_BtnExMouseMoved

    private void BtnExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExMouseClicked
       new ExcluirGerente().setVisible(true);
    }//GEN-LAST:event_BtnExMouseClicked

    private void BtnExMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExMouseExited
        ExitBtnEx();
    }//GEN-LAST:event_BtnExMouseExited

    private void BtnCadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCadMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCadMouseEntered

    private void BtnCad1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCad1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCad1MouseMoved

    private void BtnCad1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCad1MouseClicked
        new CadastrarMesas().setVisible(true);
        
    }//GEN-LAST:event_BtnCad1MouseClicked

    private void BtnCad1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCad1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCad1MouseEntered

    private void BtnCad1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCad1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCad1MouseExited

    private void BtnEx1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEx1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEx1MouseMoved

    private void BtnEx1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEx1MouseClicked
        new ExcluirMesa().setVisible(true);
    }//GEN-LAST:event_BtnEx1MouseClicked

    private void BtnEx1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEx1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEx1MouseExited

    private void BtnCon1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCon1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCon1MouseMoved

    private void BtnCon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCon1MouseClicked
        new ConsultarMesas().setVisible(true);
    }//GEN-LAST:event_BtnCon1MouseClicked

    private void BtnCon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCon1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCon1MouseExited
    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnAl;
    private javax.swing.JPanel BtnCad;
    private javax.swing.JPanel BtnCad1;
    private javax.swing.JPanel BtnCon;
    private javax.swing.JPanel BtnCon1;
    private javax.swing.JPanel BtnEx;
    private javax.swing.JPanel BtnEx1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
