/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Cadastrar;

import DAO.ConexaoDAO;
import DAO.GarcomDAO;
import Modelo.Garcom;
import Principal.MenuGerente;
import Visao.Alterar.AlterarGarcom;
import Visao.Alterar.AlterarGerente;
import Visao.Consultar.ConsultarGarcon;
import Visao.Excluir.ExcluirGarcom;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cleil
 */
public class CadastraGarcom extends javax.swing.JFrame {

    /**
     * Creates new form CadastraGarcom
     */
    public CadastraGarcom() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel32 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        txtTelefone1 = new javax.swing.JFormattedTextField();
        txtNome1 = new javax.swing.JTextField();
        txtBairro1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtCpf1 = new javax.swing.JFormattedTextField();
        jLabel49 = new javax.swing.JLabel();
        txtComboGrau = new javax.swing.JComboBox();
        jLabel52 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtLogin1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        txtSenha1 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtCep1 = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(248, 2, 39));
        jLabel28.setText("Cadastrar Garçom");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        txtNumero1.setBackground(new java.awt.Color(0, 51, 51));
        txtNumero1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNumero1.setForeground(new java.awt.Color(255, 255, 255));
        txtNumero1.setBorder(null);
        txtNumero1.setSelectionColor(new java.awt.Color(255, 2, 25));
        jPanel1.add(txtNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 60, -1));

        txtTelefone1.setBackground(new java.awt.Color(0, 51, 51));
        txtTelefone1.setBorder(null);
        txtTelefone1.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtTelefone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtTelefone1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefone1.setSelectionColor(new java.awt.Color(255, 2, 25));
        jPanel1.add(txtTelefone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 170, 20));

        txtNome1.setBackground(new java.awt.Color(0, 51, 51));
        txtNome1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNome1.setForeground(new java.awt.Color(255, 255, 255));
        txtNome1.setBorder(null);
        txtNome1.setSelectionColor(new java.awt.Color(252, 3, 18));
        jPanel1.add(txtNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 170, -1));

        txtBairro1.setBackground(new java.awt.Color(0, 51, 51));
        txtBairro1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBairro1.setForeground(new java.awt.Color(255, 255, 255));
        txtBairro1.setBorder(null);
        txtBairro1.setSelectionColor(new java.awt.Color(252, 3, 18));
        jPanel1.add(txtBairro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 180, -1));

        jLabel43.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 0, 23));
        jLabel43.setText("Rua");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        txtRua.setBackground(new java.awt.Color(0, 51, 51));
        txtRua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtRua.setForeground(new java.awt.Color(255, 255, 255));
        txtRua.setBorder(null);
        txtRua.setSelectionColor(new java.awt.Color(255, 2, 25));
        jPanel1.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 170, -1));

        jLabel44.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 0, 38));
        jLabel44.setText("CEP:");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel45.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(253, 1, 31));
        jLabel45.setText("Telefone:");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/garçom.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel40.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(252, 5, 35));
        jLabel40.setText("N°");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jLabel41.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(252, 5, 35));
        jLabel41.setText("Nome:");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel42.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(252, 5, 35));
        jLabel42.setText("Bairro");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        txtCpf1.setBackground(new java.awt.Color(0, 51, 51));
        txtCpf1.setBorder(null);
        txtCpf1.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtCpf1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCpf1.setSelectionColor(new java.awt.Color(255, 2, 25));
        jPanel1.add(txtCpf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 180, 20));

        jLabel49.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(251, 0, 15));
        jLabel49.setText("CPF:");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, -1));

        txtComboGrau.setBackground(new java.awt.Color(0, 51, 51));
        txtComboGrau.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Ensino Fundamental Incompleto", "Ensino Fundamental Completo", "Ensino Médio Incompleto", "Ensino Médio Completo", "Cursando Ensino Superior", "Ensino Superior Incompleto", "Ensino Superior Completo" }));
        txtComboGrau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComboGrauActionPerformed(evt);
            }
        });
        jPanel1.add(txtComboGrau, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 190, -1));

        jLabel52.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(252, 5, 35));
        jLabel52.setText("Data Nasc.");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(251, 0, 15));
        jLabel48.setText("Grau Escolar.");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        txtLogin1.setBackground(new java.awt.Color(0, 51, 51));
        txtLogin1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLogin1.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin1.setBorder(null);
        txtLogin1.setSelectionColor(new java.awt.Color(255, 2, 25));
        txtLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogin1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 170, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(251, 0, 15));
        jLabel50.setText("Login:");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(251, 0, 15));
        jLabel51.setText("Senha:");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, -1, -1));

        txtSenha1.setBackground(new java.awt.Color(0, 51, 51));
        txtSenha1.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha1.setBorder(null);
        txtSenha1.setSelectionColor(new java.awt.Color(252, 3, 33));
        jPanel1.add(txtSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 180, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 170, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 170, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 170, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 170, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 170, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 60, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 180, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 180, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 180, 10));

        jPanel2.setBackground(new java.awt.Color(248, 218, 2));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Limpar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, -1, 40));

        jPanel3.setBackground(new java.awt.Color(255, 51, 0));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cancelar");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 110, 40));

        jPanel4.setBackground(new java.awt.Color(51, 255, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cadastrar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, 100, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/rubbish-bin.png"))); // NOI18N
        jLabel8.setText("Excluir");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/plus.png"))); // NOI18N
        jLabel17.setText("Consultar");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pencil-edit-button.png"))); // NOI18N
        jLabel18.setText("Alterar");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/home-icon-silhouette (1).png"))); // NOI18N
        jLabel19.setText("Início");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 190, 10));

        txtCep1.setBackground(new java.awt.Color(0, 51, 51));
        txtCep1.setBorder(null);
        txtCep1.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtCep1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCep1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 170, 20));

        jFormattedTextField1.setBackground(new java.awt.Color(0, 51, 51));
        jFormattedTextField1.setBorder(null);
        jFormattedTextField1.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 190, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 650, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtComboGrauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComboGrauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComboGrauActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked

        dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
           if(txtComboGrau.getSelectedItem().toString() == "Selecione.."){
            JOptionPane.showMessageDialog(null, "Por favor, selecione o tipo de Usuário","Sistema Restaurante", JOptionPane.ERROR_MESSAGE);
        }
        
        String nome = txtNome1.getText();
        String bairro  = txtBairro1.getText();
        String dataNasc = jFormattedTextField1.getText();
        String cep = txtCep1.getText();
        String rua = txtRua.getText();
        String telefone = txtTelefone1.getText();
        String numero = txtNumero1.getText();
        String cpf = txtCpf1.getText();
        String grau = txtComboGrau.getSelectedItem().toString();
        String login = txtLogin1.getText();
        String senha = txtSenha1.getText();

        if(nome.equals("") || bairro.equals("") || cep.equals("") || 
            numero.equals("") || bairro.equals("") || telefone.equals("") || cpf.equals("") ||
            login.equals("") || senha.equals("") ){
            JOptionPane.showMessageDialog(null,"Nenhum Campo pode Estar Vazio!","Sistema Restaurante",JOptionPane.WARNING_MESSAGE);
        }else{
            Connection con = ConexaoDAO.AbrirConexao();
            GarcomDAO sql = new GarcomDAO(con);
            int n = Integer.parseInt(numero);

            Garcom a  = new Garcom();

            a.setNome(nome);
            a.setData_nasc(dataNasc);
            a.setTelefone(telefone);
            a.setBairro(bairro);
            a.setRua(rua);
            a.setNumero(n);
            a.setCep(cep);
            a.setGrau_escolaridade(grau);
            a.setCpf(cpf);
            a.setLogin(login);
            a.setSenha(senha);

            String resultado =  sql.inserir_Garcom(a);

            System.out.println(resultado);
            ConexaoDAO.FecharConexao(con);

            txtNome1.setText("");
            txtBairro1.setText("");
            jFormattedTextField1.setText("");
            txtRua.setText("");
            txtNumero1.setText("");
            txtCep1.setText("");
            txtTelefone1.setText("");
            txtCpf1.setText("");
            txtComboGrau.setSelectedItem("");
            txtLogin1.setText("");
            txtSenha1.setText("");

            JOptionPane.showMessageDialog(null,"Cadastro realizado com Sucesso!","Sistema de Restaurante",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
            txtNome1.setText("");
            txtBairro1.setText("");
            jFormattedTextField1.setText("");
            txtRua.setText("");
            txtNumero1.setText("");
            txtCep1.setText("");
            txtTelefone1.setText("");
            txtCpf1.setText("");
            txtComboGrau.setSelectedItem("");
            txtLogin1.setText("");
            txtSenha1.setText("");

    }//GEN-LAST:event_jPanel2MouseClicked

    private void txtLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLogin1ActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        new MenuGerente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
       new AlterarGarcom().setVisible(true);
       
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
       new ConsultarGarcon().setVisible(true);
       
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        new ExcluirGarcom().setVisible(true);
       
    }//GEN-LAST:event_jLabel8MouseClicked

    private void txtCep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCep1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCep1ActionPerformed
     private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastraGarcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastraGarcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastraGarcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastraGarcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastraGarcom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtBairro1;
    private javax.swing.JFormattedTextField txtCep1;
    private javax.swing.JComboBox txtComboGrau;
    private javax.swing.JFormattedTextField txtCpf1;
    private javax.swing.JTextField txtLogin1;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtRua;
    private javax.swing.JPasswordField txtSenha1;
    private javax.swing.JFormattedTextField txtTelefone1;
    // End of variables declaration//GEN-END:variables
}
