/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Alterar;

import DAO.ConexaoDAO;
import DAO.GarcomDAO;
import Modelo.Garcom;
import Principal.MenuGerente;
import Visao.Cadastrar.CadastraGarcom;
import Visao.Consultar.ConsultarGarcon;
import Visao.Excluir.ExcluirGarcom;
import java.awt.Toolkit;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cleil
 */
public class AlterarGarcom extends javax.swing.JFrame {

    /**
     * Creates new form AlteraGarcom
     */
    public AlterarGarcom() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIcon();
    }
    private void InserirDados(int cod) {
        Connection con = ConexaoDAO.AbrirConexao();
        GarcomDAO sql = new GarcomDAO(con);
        List<Garcom> lista = new ArrayList<>();
        lista = sql.CapturarGarcom(cod);

        for (Garcom a : lista) {
            iptId2.setText("" + a.getId());
            iptNome2.setText(a.getNome());
            iptData_nasc1.setText(a.getData_nasc());
            iptTelefone2.setText(a.getTelefone());
            iptRua2.setText(a.getRua());
            iptBairro2.setText(a.getBairro());
            iptCEP2.setText(a.getCep());
            iptNumero2.setText("" + a.getNumero());
            iptGrau_escolaridade1.setSelectedItem(a.getGrau_escolaridade());
            iptCPF2.setText(a.getCpf()); 
            iptLogin2.setText(a.getLogin());
            iptSenha2.setText(a.getSenha());
             
           

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        iptBairro2 = new javax.swing.JTextField();
        iptNome2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        iptRua2 = new javax.swing.JTextField();
        iptTelefone2 = new javax.swing.JFormattedTextField();
        iptNumero2 = new javax.swing.JTextField();
        iptCEP2 = new javax.swing.JFormattedTextField();
        iptCPF2 = new javax.swing.JFormattedTextField();
        iptLogin2 = new javax.swing.JTextField();
        iptSenha2 = new javax.swing.JPasswordField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        attCod2 = new javax.swing.JTextField();
        labelId2 = new javax.swing.JLabel();
        iptId2 = new javax.swing.JTextField();
        iptGrau_escolaridade1 = new javax.swing.JComboBox();
        iptData_nasc1 = new javax.swing.JFormattedTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(0, 51, 51));
        jPanel14.setInheritsPopupMenu(true);
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(238, 49, 38));
        jLabel14.setText("Nome :");
        jPanel14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel32.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(238, 49, 38));
        jLabel32.setText("Telefone :");
        jPanel14.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel33.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(238, 49, 38));
        jLabel33.setText("Grau Escolar. :");
        jPanel14.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel34.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(238, 49, 38));
        jLabel34.setText("Data Nasc. :");
        jPanel14.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel35.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(238, 49, 38));
        jLabel35.setText("CPF :");
        jPanel14.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabel36.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(238, 49, 38));
        jLabel36.setText("Login :");
        jPanel14.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jLabel37.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(238, 49, 38));
        jLabel37.setText("Senha :");
        jPanel14.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        iptBairro2.setBackground(new java.awt.Color(0, 51, 51));
        iptBairro2.setForeground(new java.awt.Color(255, 255, 255));
        iptBairro2.setBorder(null);
        jPanel14.add(iptBairro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 151, 20));

        iptNome2.setBackground(new java.awt.Color(0, 51, 51));
        iptNome2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        iptNome2.setForeground(new java.awt.Color(255, 255, 255));
        iptNome2.setBorder(null);
        iptNome2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                iptNome2iptNome1FocusGained(evt);
            }
        });
        iptNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptNome2iptNome1ActionPerformed(evt);
            }
        });
        jPanel14.add(iptNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 280, 20));

        jLabel38.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(238, 49, 38));
        jLabel38.setText("Bairro :");
        jPanel14.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel39.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(238, 49, 38));
        jLabel39.setText("Rua :");
        jPanel14.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jLabel40.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(238, 49, 38));
        jLabel40.setText("Nº :");
        jPanel14.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jLabel41.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(238, 49, 38));
        jLabel41.setText("CEP :");
        jPanel14.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        iptRua2.setBackground(new java.awt.Color(0, 51, 51));
        iptRua2.setForeground(new java.awt.Color(255, 255, 255));
        iptRua2.setBorder(null);
        jPanel14.add(iptRua2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 70, 20));

        iptTelefone2.setBackground(new java.awt.Color(0, 51, 51));
        iptTelefone2.setBorder(null);
        iptTelefone2.setForeground(new java.awt.Color(255, 255, 255));
        try {
            iptTelefone2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel14.add(iptTelefone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 151, 30));

        iptNumero2.setBackground(new java.awt.Color(0, 51, 51));
        iptNumero2.setForeground(new java.awt.Color(255, 255, 255));
        iptNumero2.setBorder(null);
        iptNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptNumero2iptNumero1ActionPerformed(evt);
            }
        });
        jPanel14.add(iptNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 70, 20));

        iptCEP2.setBackground(new java.awt.Color(0, 51, 51));
        iptCEP2.setBorder(null);
        iptCEP2.setForeground(new java.awt.Color(255, 255, 255));
        try {
            iptCEP2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel14.add(iptCEP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 110, 20));

        iptCPF2.setBackground(new java.awt.Color(0, 51, 51));
        iptCPF2.setBorder(null);
        iptCPF2.setForeground(new java.awt.Color(255, 255, 255));
        try {
            iptCPF2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel14.add(iptCPF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 280, 20));

        iptLogin2.setBackground(new java.awt.Color(0, 51, 51));
        iptLogin2.setForeground(new java.awt.Color(255, 255, 255));
        iptLogin2.setBorder(null);
        jPanel14.add(iptLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 280, 20));

        iptSenha2.setBackground(new java.awt.Color(0, 51, 51));
        iptSenha2.setForeground(new java.awt.Color(255, 255, 255));
        iptSenha2.setBorder(null);
        jPanel14.add(iptSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 280, 20));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/rotate.png"))); // NOI18N
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        jLabel43.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(238, 49, 38));
        jLabel43.setText("Código:");
        jPanel14.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        attCod2.setBackground(new java.awt.Color(51, 255, 255));
        attCod2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                attCod2attCod1FocusGained(evt);
            }
        });
        attCod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attCod2attCod1ActionPerformed(evt);
            }
        });
        jPanel14.add(attCod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 50, 40));

        labelId2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelId2.setForeground(new java.awt.Color(238, 49, 38));
        labelId2.setText("Id :");
        jPanel14.add(labelId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, -1));

        iptId2.setBackground(new java.awt.Color(0, 51, 51));
        iptId2.setForeground(new java.awt.Color(255, 255, 255));
        iptId2.setBorder(null);
        iptId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptId2iptId1ActionPerformed(evt);
            }
        });
        jPanel14.add(iptId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 40, 20));

        iptGrau_escolaridade1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Ensino Fundamental Incompleto", "Ensino Fundamental Completo", "Ensino Médio Incompleto", "Ensino Médio Completo", "Cursando Ensino Superior", "Ensino Superior Incompleto", "Ensino Superior Completo" }));
        iptGrau_escolaridade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptGrau_escolaridade1iptGrau_escolaridadeActionPerformed(evt);
            }
        });
        jPanel14.add(iptGrau_escolaridade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 280, 23));

        iptData_nasc1.setBackground(new java.awt.Color(0, 51, 51));
        iptData_nasc1.setBorder(null);
        iptData_nasc1.setForeground(new java.awt.Color(255, 255, 255));
        try {
            iptData_nasc1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel14.add(iptData_nasc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 280, 20));

        jPanel11.setBackground(new java.awt.Color(0, 255, 0));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11jPanel5MouseClicked(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifier-tool.png"))); // NOI18N
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel14.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 40, 40));
        jPanel14.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 280, 10));
        jPanel14.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 70, 10));
        jPanel14.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 280, 10));
        jPanel14.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 280, 10));
        jPanel14.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 280, 10));
        jPanel14.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 280, 10));
        jPanel14.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, 10));
        jPanel14.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 70, 10));
        jPanel14.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 150, 10));
        jPanel14.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 10));
        jPanel14.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 40, 10));

        jPanel13.setBackground(new java.awt.Color(240, 240, 27));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(240, 240, 27));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Limpar");
        jPanel12.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel13.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 90, 40));

        jPanel20.setBackground(new java.awt.Color(240, 240, 27));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Limpar");
        jPanel20.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel19.setBackground(new java.awt.Color(240, 240, 27));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Limpar");
        jPanel19.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel20.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 90, 40));

        jPanel13.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 90, 40));

        jLabel44.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Limpar");
        jPanel13.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel14.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 110, 40));

        jPanel21.setBackground(new java.awt.Color(255, 0, 0));
        jPanel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel21jPanel18MouseClicked(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Cancelar");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel48)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel48)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel14.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, 40));

        jPanel10.setBackground(new java.awt.Color(102, 255, 0));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alterar");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel14.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 100, 40));

        jLabel31.setFont(new java.awt.Font("Baking Lion - Personal Use", 2, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 153, 153));
        jLabel31.setText("Restaurante 2019");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 200, -1));

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/rubbish-bin.png"))); // NOI18N
        jLabel9.setText("Excluir");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/plus.png"))); // NOI18N
        jLabel17.setText("Cadastrar");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pencil-edit-button.png"))); // NOI18N
        jLabel19.setText("Consultar");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/home-icon-silhouette (1).png"))); // NOI18N
        jLabel20.setText("Início");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("AlterarGarçom");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remove.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remove-button.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel20)
                .addGap(12, 12, 12)
                .addComponent(jLabel19)
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addGap(11, 11, 11)
                .addComponent(jLabel9)
                .addGap(114, 114, 114)
                .addComponent(jLabel13)
                .addGap(104, 104, 104)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel13))
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18))
        );

        jPanel14.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 60));

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iptNome2iptNome1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_iptNome2iptNome1FocusGained

    }//GEN-LAST:event_iptNome2iptNome1FocusGained

    private void iptNome2iptNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptNome2iptNome1ActionPerformed

    }//GEN-LAST:event_iptNome2iptNome1ActionPerformed

    private void iptNumero2iptNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptNumero2iptNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptNumero2iptNumero1ActionPerformed

    private void attCod2attCod1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_attCod2attCod1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_attCod2attCod1FocusGained

    private void attCod2attCod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attCod2attCod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attCod2attCod1ActionPerformed

    private void iptId2iptId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptId2iptId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptId2iptId1ActionPerformed

    private void iptGrau_escolaridade1iptGrau_escolaridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptGrau_escolaridade1iptGrau_escolaridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptGrau_escolaridade1iptGrau_escolaridadeActionPerformed

    private void jPanel11jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11jPanel5MouseClicked
        String codigo = attCod2.getText();
        Connection con = ConexaoDAO.AbrirConexao();
        GarcomDAO sql = new GarcomDAO(con);

        if (codigo.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um Código para Atualizar", "Sistema Restaurante", JOptionPane.WARNING_MESSAGE);
        } else {
            int cod = Integer.parseInt(codigo);
            if (sql.TestarGarcom(cod) == false) {
                JOptionPane.showMessageDialog(null, "Código não encontrado no Banco", "Sistema Restaurante", JOptionPane.ERROR_MESSAGE);
                ConexaoDAO.FecharConexao(con);
            }

            iptNome2.setText("");
            iptBairro2.setText("");
            iptCEP2.setText("");
            iptCPF2.setText("");
            iptRua2.setText("");
            iptNumero2.setText("");
            iptGrau_escolaridade1.setSelectedItem("Selecione...");
            iptTelefone2.setText("");
            iptLogin2.setText("");
            iptSenha2.setText("");
            iptId2.setText("");
            iptData_nasc1.setText("");

            InserirDados(cod);
            attCod2.setText("");
        }
    }//GEN-LAST:event_jPanel11jPanel5MouseClicked

    private void jPanel21jPanel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel21jPanel18MouseClicked
        dispose();
    }//GEN-LAST:event_jPanel21jPanel18MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked

        String nome = iptNome2.getText();
        String cep = iptCEP2.getText();
        String rua = iptRua2.getText();
        String numero = iptNumero2.getText();
        String bairro = iptBairro2.getText();
        String Grau_escolaridade = (String) iptGrau_escolaridade1.getSelectedItem();
        String fone = iptTelefone2.getText();
        String cpf = iptCPF2.getText();
        String Data_nasc = iptData_nasc1.getText();
        String login = iptLogin2.getText();
        String senha = iptSenha2.getText();
        String id = iptId2.getText();
        int idN = Integer.parseInt(id);

        if (nome.equals("") || cep.equals("") || rua.equals("") || numero.equals("") || bairro.equals("") || fone.equals("") || cpf.equals("") || Grau_escolaridade.equals("") || login.equals("") || senha.equals("") || Data_nasc.equals("")) {
            JOptionPane.showMessageDialog(null, "Nenhum Campo pode Estar Vazio!", "Sistema Restaurante", JOptionPane.WARNING_MESSAGE);
        } else {
            Connection con = ConexaoDAO.AbrirConexao();
            GarcomDAO sql = new GarcomDAO(con);
            int n = Integer.parseInt(numero);

            Garcom a = new Garcom();

            a.setBairro(bairro);
            a.setCep(cep);
            a.setCpf(cpf);
            a.setGrau_escolaridade(Grau_escolaridade);
            a.setNome(nome);
            a.setNumero(n);
            a.setData_nasc(Data_nasc);
            a.setRua(rua);
            a.setTelefone(fone);
            a.setLogin(login);
            a.setSenha(senha);
            a.setId(idN);

            String resultado = sql.AlterarGarcom(a);

            System.out.println(resultado);
            ConexaoDAO.FecharConexao(con);

            iptNome2.setText("");
            iptCEP2.setText("");
            iptNumero2.setText("");
            iptBairro2.setText("");
            iptGrau_escolaridade1.setSelectedItem("");
            iptTelefone2.setText("");
            iptRua2.setText("");
            iptData_nasc1.setText("");
            iptCPF2.setText("");
            iptLogin2.setText("");
            iptSenha2.setText("");
            iptId2.setText("");

            JOptionPane.showMessageDialog(null, "Alteração Realizada com Sucesso!", "Video Locadora", JOptionPane.INFORMATION_MESSAGE);

            

        }
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked

    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        new ExcluirGarcom().setVisible(true);
       
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        new CadastraGarcom().setVisible(true);
       
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        new ConsultarGarcon().setVisible(true);
        
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
     dispose();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
            iptNome2.setText("");
            iptCEP2.setText("");
            iptNumero2.setText("");
            iptBairro2.setText("");
            iptGrau_escolaridade1.setSelectedItem("");
            iptTelefone2.setText("");
            iptRua2.setText("");
            iptData_nasc1.setText("");
            iptCPF2.setText("");
            iptLogin2.setText("");
            iptSenha2.setText("");
            iptId2.setText("");
    }//GEN-LAST:event_jPanel13MouseClicked
     private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarGarcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarGarcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarGarcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarGarcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarGarcom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attCod2;
    private javax.swing.JTextField iptBairro2;
    private javax.swing.JFormattedTextField iptCEP2;
    private javax.swing.JFormattedTextField iptCPF2;
    private javax.swing.JFormattedTextField iptData_nasc1;
    private javax.swing.JComboBox iptGrau_escolaridade1;
    private javax.swing.JTextField iptId2;
    private javax.swing.JTextField iptLogin2;
    private javax.swing.JTextField iptNome2;
    private javax.swing.JTextField iptNumero2;
    private javax.swing.JTextField iptRua2;
    private javax.swing.JPasswordField iptSenha2;
    private javax.swing.JFormattedTextField iptTelefone2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JLabel labelId2;
    // End of variables declaration//GEN-END:variables
}
